name: "Generate awesome text"
description: "Generate awesome text with Google Gemini model"
author: huuquyet

# Add your action's branding here. This will appear on the GitHub Marketplace. Icons from https://feathericons.com/
branding:
  icon: "file-text"
  color: "yellow"

# Enter the prompt in order to chat with Gemini model
inputs:
  prompt: # id of input
    description: "Input prompt send to the action"
    required: true
    default: "Please tell a hilarious dad joke for kids about the weather today"

# Ouput generated result to use later
outputs:
  result:
    description: "The generated result by Gemini model for later using"

runs:
  using: "node20"
  main: dist/index.js
