name: generate-awesome-text

on:
  # Run automatically everyday at 00:10
  # schedule:
  # - cron: "10 0 * * *"
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  # Run on every push or pull request on main branch
  # push:
  #   branches: [ "main" ]

permissions:
  contents: write

# Only a single workflow in the same concurrency will run at the same time
# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
#   cancel-in-progress: true

jobs:
  generate_text:
    name: Generate awesome text with Javascript
    runs-on: ubuntu-latest

    steps:
    # Checkout the main branch
    - uses: actions/checkout@v4

    # Uses action in the root directory to generate awesome text
    - name: Generate awesome text
      uses: huuquyet/generate-awesome-text@main
      env: 
        GEMINI_API_TOKEN: ${{ secrets.GEMINI_API_TOKEN }}
      with:
        prompt: "Please tell a hilarious dad joke about baby shark"

    # Push awesome text to main branch
    # Note: the following account information will not work on GHES
    - name: Push the awesome text to main branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m ":robot: Generated awesome text"
        git push
